# Generated by Django 6.0.2 on 2026-07-06 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('url', models.URLField(verbose_name='URL')),
                ('category', models.CharField(choices=[('youtube', 'YouTube'), ('article', '記事'), ('sns', 'SNS'), ('shopping', '商品ページ'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ')),
                ('release_at', models.DateTimeField(verbose_name='解放日時')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
